logo_url: /favicon/favicon-light-192.png

media_folder: "/src/content/posts/images" # 文件将被存储在仓库中的位置
# public_folder: "src/content/posts/images" # 上传媒体文件的 src 属性

collections:
  - name: "Posts" # 用于路由，例如，/admin/collections/blog
    label: "文章" # 在 UI 中使用
    folder: "src/content/posts" # 存储文档的文件夹路径
    create: true # 允许用户在此集合中创建新文档
    fields: # 每个文档的字段，通常在 front matter 中
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime", type: "date" }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "封面图片", name: "image", widget: "image", default: "https://rdimg.yumehinata.com/random-wallpaper"}
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "category", widget: "relation", collection: "Categories", value_field: "slug", display_fields: ["title"], search_fields: ["title"]}
      - { label: "草稿状态", name: "draft", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "richtext" }
      # - { label: "正文", name: "body", widget: "vditor-markdown" }
    media_folder: "/src/content/posts/images/{{slug}}" # 文件将被存储在仓库中的位置
    public_folder: "./images/{{slug}}" # 上传媒体文件的 src 属性
  - name: Categories
    label: "分类管理"
    folder: "src/content/categories" # 存放分类文件的独立文件夹
    create: true                     # 允许你在后台随时新增、修改或删除分类
    fields:
      - { label: "分类名称", name: "title", widget: "string", required: true }
      - { label: "分类别名", name: "slug", widget: "string", required: true }
    icon: "category"
  - name: "Config"
    label: "Sveltia配置文件"
    files:
      - name: "sveltia_config"
        label: "config.yml"
        file: "/public/admin/config.yml"
        format: raw
        fields:
        - { label: "config.yml", name: "body", widget: "text"}
    icon: "tune"
    

# publish_mode: editorial_workflow
i18n:
  structure: multiple_folders
  locales: ["zh-cn", "en"]
  default_locale: "zh-cn"
backend:
  name: github
  repo: "YumeHinata/AstroBlog"
  branch: "main"
  api_root: "https://api.github.com"
  site_domain: "https://www.yumehinata.com"
  base_url: "https://www.yumehinata.com"
  auth_endpoint: "auth"