logo_url: /favicon/favicon-light-192.png

# 全局媒体目录
media_folder: "/src/content/posts/images"
collections:
  # 文章
  - name: "Posts"
    label: "文章"
    folder: "src/content/posts"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime", type: "date" }
      - {
          label: "描述",
          name: "description",
          widget: "text",
          required: false
        }
      - {
          label: "封面图片",
          name: "image",
          widget: "image",
          default: "https://rdimg.yumehinata.com/random-wallpaper"
        }
      - {
          label: "标签",
          name: "tags",
          widget: "list",
          required: false
        }
      - {
          label: "分类",
          name: "category",
          widget: "relation",
          collection: "Categories",
          value_field: "slug",
          display_fields: ["title"],
          search_fields: ["title"]
        }
      - {
          label: "草稿状态",
          name: "draft",
          widget: "boolean",
          default: false
        }
      - {
          label: "正文",
          name: "body",
          widget: "richtext"
        }
    # Fuwari 所需的图片目录结构
    media_folder: "/src/content/posts/images/{{slug}}"
    public_folder: "./images/{{slug}}"

  # 分类
  - name: "Categories"
    label: "分类管理"
    folder: "src/content/categories"
    create: true
    fields:
      - {
          label: "分类名称",
          name: "title",
          widget: "string",
          required: true
        }
      - {
          label: "分类别名",
          name: "slug",
          widget: "string",
          required: true
        }
    icon: "category"

  # Sveltia 配置文件
  - name: "Config"
    label: "Sveltia配置文件"
    icon: "tune"
    editor:
      preview: false
    files:
      - name: "sveltia_config"
        label: "config.yml"
        file: "/public/admin/config.yml"
        format: raw
        fields:
          - name: "body"
            label: "config.yml"
            widget: "code"
            output_code_only: true
            allow_language_selection: false
            default_language: "yaml"

# 国际化
i18n:
  structure: multiple_folders
  locales: ["zh-cn", "en"]
  default_locale: "zh-cn"

# GitHub Backend
backend:
  name: github
  repo: "YumeHinata/AstroBlog"
  branch: "main"

  api_root: "https://api.github.com"

  site_domain: "https://www.yumehinata.com"
  base_url: "https://www.yumehinata.com"

  auth_endpoint: "auth"

# publish_mode: editorial_workflow
